/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.BorderLayout;
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.xy.IntervalXYDataset;
import org.jfree.data.statistics.HistogramDataset;


/**
 *
 * @author mohiu
 */





public class Statistics extends javax.swing.JFrame {

    /**
     * Creates new form Statistics
     * 
     * 
     * 
     */
    
    
    
    
    public Statistics() {
        initComponents();
        getContentPane().setBackground(new Color(250,250,250));
        showPieChart();
        showHistogram();
    }
    
    
    private void showPieChart(){
        
        //create dataset
      DefaultPieDataset barDataset = new DefaultPieDataset( );
      barDataset.setValue( "Food" , new Double( 70 ) );  
      barDataset.setValue( "AutoMobile" , new Double( 50 ) );   
      barDataset.setValue( "Shopping" , new Double( 90 ) ); 
      barDataset.setValue( "Clothing" , new Double( 60 ) ); 
      barDataset.setValue( "Investment" , new Double( 80 ) ); 
      barDataset.setValue( "Others" , new Double( 40 ) );  
      
      //create chart
       JFreeChart piechart = ChartFactory.createPieChart("",barDataset, false,false,false);//explain
      
        PiePlot piePlot =(PiePlot) piechart.getPlot();
      
       //changing pie chart blocks colors
       piePlot.setSectionPaint("Food", new Color(255,255,102));
        piePlot.setSectionPaint("AutoMobile", new Color(102,255,102));
        piePlot.setSectionPaint("Shopping", new Color(255,102,153));
        piePlot.setSectionPaint("Clothing", new Color(255,141,160));
        piePlot.setSectionPaint("Investment", new Color(147,120,190));
        piePlot.setSectionPaint("Others", new Color(0,204,204));
      
       
        piePlot.setBackgroundPaint(Color.white);
        piePlot.setOutlinePaint(null);
        
        //create chartPanel to display chart(graph)
        ChartPanel barChartPanel = new ChartPanel(piechart);
        panelBarChart.removeAll();
        panelBarChart.add(barChartPanel, BorderLayout.CENTER);
        panelBarChart.validate();
        
    }
    
    private void showHistogram(){
        
         double[] values = { 95, 49, 14, 59, 50, 66, 47, 40, 1, 67,
                            12, 58, 28, 63, 14, 9, 31, 17, 94, 71,
                            49, 64, 73, 97, 15, 63, 10, 12, 31, 62,
                            93, 49, 74, 90, 59, 14, 15, 88, 26, 57,
                            77, 44, 58, 91, 10, 67, 57, 19, 88, 84                                
                          };
 
 
        HistogramDataset dataset = new HistogramDataset();
        dataset.addSeries("key", values, 20);
        
         JFreeChart chart = ChartFactory.createHistogram("Monthly Expense Histogram","Total Money", "Expense", (IntervalXYDataset) dataset,PlotOrientation.VERTICAL, false,true,false);
            XYPlot plot= chart.getXYPlot();
        plot.setBackgroundPaint(Color.WHITE);

        
        
        ChartPanel barpChartPanel2 = new ChartPanel(chart);
        HistogramPanel.removeAll();
        HistogramPanel.add(barpChartPanel2, BorderLayout.CENTER);
        HistogramPanel.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarChart = new java.awt.Panel();
        HistogramPanel = new java.awt.Panel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jPanel11 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        jPanel16 = new javax.swing.JPanel();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        label19 = new java.awt.Label();
        jPanel17 = new javax.swing.JPanel();
        label20 = new java.awt.Label();
        label21 = new java.awt.Label();
        label22 = new java.awt.Label();
        jPanel18 = new javax.swing.JPanel();
        label23 = new java.awt.Label();
        label24 = new java.awt.Label();
        label25 = new java.awt.Label();
        jPanel12 = new javax.swing.JPanel();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        jPanel13 = new javax.swing.JPanel();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        jPanel14 = new javax.swing.JPanel();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        jPanel15 = new javax.swing.JPanel();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        jPanel19 = new javax.swing.JPanel();
        label26 = new java.awt.Label();
        label27 = new java.awt.Label();
        label28 = new java.awt.Label();
        jPanel20 = new javax.swing.JPanel();
        label29 = new java.awt.Label();
        label30 = new java.awt.Label();
        label31 = new java.awt.Label();
        jPanel21 = new javax.swing.JPanel();
        label32 = new java.awt.Label();
        label33 = new java.awt.Label();
        label34 = new java.awt.Label();
        jPanel22 = new javax.swing.JPanel();
        label35 = new java.awt.Label();
        label36 = new java.awt.Label();
        label37 = new java.awt.Label();
        jPanel23 = new javax.swing.JPanel();
        label38 = new java.awt.Label();
        label39 = new java.awt.Label();
        label40 = new java.awt.Label();
        jPanel24 = new javax.swing.JPanel();
        label41 = new java.awt.Label();
        label42 = new java.awt.Label();
        label43 = new java.awt.Label();
        jPanel25 = new javax.swing.JPanel();
        label44 = new java.awt.Label();
        label45 = new java.awt.Label();
        label46 = new java.awt.Label();
        jPanel26 = new javax.swing.JPanel();
        label47 = new java.awt.Label();
        label48 = new java.awt.Label();
        label49 = new java.awt.Label();
        jPanel27 = new javax.swing.JPanel();
        label50 = new java.awt.Label();
        label51 = new java.awt.Label();
        label52 = new java.awt.Label();
        jPanel28 = new javax.swing.JPanel();
        label53 = new java.awt.Label();
        label54 = new java.awt.Label();
        label55 = new java.awt.Label();
        jPanel29 = new javax.swing.JPanel();
        label56 = new java.awt.Label();
        label57 = new java.awt.Label();
        label58 = new java.awt.Label();
        jPanel30 = new javax.swing.JPanel();
        label59 = new java.awt.Label();
        label60 = new java.awt.Label();
        label61 = new java.awt.Label();
        jPanel31 = new javax.swing.JPanel();
        label62 = new java.awt.Label();
        label63 = new java.awt.Label();
        label64 = new java.awt.Label();
        jPanel32 = new javax.swing.JPanel();
        label65 = new java.awt.Label();
        label66 = new java.awt.Label();
        label67 = new java.awt.Label();
        jPanel33 = new javax.swing.JPanel();
        label68 = new java.awt.Label();
        label69 = new java.awt.Label();
        label70 = new java.awt.Label();
        jPanel34 = new javax.swing.JPanel();
        label71 = new java.awt.Label();
        label72 = new java.awt.Label();
        label73 = new java.awt.Label();
        MenuPanel = new javax.swing.JPanel();
        rSButtonHover4 = new rojerusan.RSButtonHover();
        rSButtonHover5 = new rojerusan.RSButtonHover();
        rSButtonHover6 = new rojerusan.RSButtonHover();
        rSButtonHover7 = new rojerusan.RSButtonHover();
        rSButtonHover8 = new rojerusan.RSButtonHover();
        rSButtonHover9 = new rojerusan.RSButtonHover();
        rSButtonHover10 = new rojerusan.RSButtonHover();
        rSButtonHover11 = new rojerusan.RSButtonHover();
        rSButtonHover12 = new rojerusan.RSButtonHover();
        rSButtonHover13 = new rojerusan.RSButtonHover();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBarChart.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelBarChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 330, 170));

        HistogramPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(HistogramPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 330, 170));

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("This Week");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tk. 16,500");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 130, 70));

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Least Spent day");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tuesday");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 120, 70));

        jPanel4.setBackground(new java.awt.Color(204, 255, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("This Year");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Tk. 2,71,520");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 120, 70));

        jPanel5.setBackground(new java.awt.Color(0, 255, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("This Month");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Tk. 39,500");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, 70));

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Overall Spent");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Tk. 2,78,500");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 130, 70));

        jPanel7.setBackground(new java.awt.Color(255, 102, 102));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Today");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Tk. 4,788");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 130, 70));

        jPanel8.setBackground(new java.awt.Color(255, 0, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Most Spent On");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Shopping");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 120, 70));

        jPanel9.setBackground(new java.awt.Color(0, 102, 102));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Most Spent day");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Sunday");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 120, 70));

        jPanel10.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setText("Each Category");
        jPanel10.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel11.setFocusable(false);
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("Others");
        jPanel11.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label3.setBackground(new java.awt.Color(51, 0, 51));
        jPanel11.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, 10));

        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("2,605 Tk");
        jPanel11.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, 20));

        jPanel16.setFocusable(false);
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label17.setText("Food");
        jPanel16.add(label17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label18.setBackground(new java.awt.Color(255, 153, 0));
        jPanel16.add(label18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, 10));

        label19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label19.setText("24,050 Tk");
        jPanel16.add(label19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel11.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 160, 70));

        jPanel17.setFocusable(false);
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label20.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label20.setText("Food");
        jPanel17.add(label20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label21.setBackground(new java.awt.Color(255, 153, 0));
        jPanel17.add(label21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, 10));

        label22.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label22.setText("24,050 Tk");
        jPanel17.add(label22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel18.setFocusable(false);
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label23.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label23.setText("Food");
        jPanel18.add(label23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label24.setBackground(new java.awt.Color(255, 153, 0));
        jPanel18.add(label24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, 10));

        label25.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label25.setText("24,050 Tk");
        jPanel18.add(label25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 160, 70));

        jPanel11.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 160, 70));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 160, 70));

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setFocusable(false);
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setText("Food");
        jPanel12.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        label6.setBackground(new java.awt.Color(255, 153, 0));
        jPanel12.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, 10));

        label7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label7.setText("24,050 Tk");
        jPanel12.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, 70));

        jPanel13.setBackground(new java.awt.Color(204, 204, 204));
        jPanel13.setFocusable(false);
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label8.setText("AutoMobile");
        jPanel13.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label9.setBackground(new java.awt.Color(255, 102, 255));
        jPanel13.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, 10));

        label10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label10.setText("13,727 Tk");
        jPanel13.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jPanel10.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 160, 70));

        jPanel14.setBackground(new java.awt.Color(204, 204, 204));
        jPanel14.setFocusable(false);
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label11.setText("Entertainment");
        jPanel14.add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label12.setBackground(new java.awt.Color(255, 153, 153));
        jPanel14.add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, 10));

        label13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label13.setText("3,698 Tk");
        jPanel14.add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jPanel10.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 160, 70));

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.setFocusable(false);
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label14.setText("Clothing");
        jPanel15.add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label15.setBackground(new java.awt.Color(153, 0, 204));
        jPanel15.add(label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, 10));

        label16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label16.setText("14,725 Tk");
        jPanel15.add(label16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jPanel10.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 160, 70));

        jPanel19.setBackground(new java.awt.Color(204, 204, 204));
        jPanel19.setFocusable(false);
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label26.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label26.setName("Healthcare"); // NOI18N
        label26.setText("Shopping");
        jPanel19.add(label26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label27.setBackground(new java.awt.Color(51, 0, 255));
        jPanel19.add(label27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, 10));

        label28.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label28.setName(""); // NOI18N
        label28.setText("85,040 Tk");
        jPanel19.add(label28, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jPanel20.setFocusable(false);
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label29.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label29.setText("Food");
        jPanel20.add(label29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label30.setBackground(new java.awt.Color(255, 153, 0));
        jPanel20.add(label30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, 10));

        label31.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label31.setText("24,050 Tk");
        jPanel20.add(label31, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 160, 70));

        jPanel21.setFocusable(false);
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label32.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label32.setText("Food");
        jPanel21.add(label32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label33.setBackground(new java.awt.Color(255, 153, 0));
        jPanel21.add(label33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, 10));

        label34.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label34.setText("24,050 Tk");
        jPanel21.add(label34, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel22.setFocusable(false);
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label35.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label35.setText("Food");
        jPanel22.add(label35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label36.setBackground(new java.awt.Color(255, 153, 0));
        jPanel22.add(label36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, 10));

        label37.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label37.setText("24,050 Tk");
        jPanel22.add(label37, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel21.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 160, 70));

        jPanel19.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 160, 70));

        jPanel10.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 70));

        jPanel23.setBackground(new java.awt.Color(204, 204, 204));
        jPanel23.setFocusable(false);
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label38.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label38.setText("Healthcare");
        jPanel23.add(label38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label39.setBackground(new java.awt.Color(204, 0, 51));
        jPanel23.add(label39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, 10));

        label40.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label40.setText("400 Tk");
        jPanel23.add(label40, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jPanel24.setFocusable(false);
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label41.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label41.setText("Food");
        jPanel24.add(label41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label42.setBackground(new java.awt.Color(255, 153, 0));
        jPanel24.add(label42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, 10));

        label43.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label43.setText("24,050 Tk");
        jPanel24.add(label43, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel23.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 160, 70));

        jPanel25.setFocusable(false);
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label44.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label44.setText("Food");
        jPanel25.add(label44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label45.setBackground(new java.awt.Color(255, 153, 0));
        jPanel25.add(label45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, 10));

        label46.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label46.setText("24,050 Tk");
        jPanel25.add(label46, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel26.setFocusable(false);
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label47.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label47.setText("Food");
        jPanel26.add(label47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label48.setBackground(new java.awt.Color(255, 153, 0));
        jPanel26.add(label48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, 10));

        label49.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label49.setText("24,050 Tk");
        jPanel26.add(label49, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel25.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 160, 70));

        jPanel23.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 160, 70));

        jPanel10.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 160, 70));

        jPanel27.setBackground(new java.awt.Color(204, 204, 204));
        jPanel27.setFocusable(false);
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label50.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label50.setText("Investment");
        jPanel27.add(label50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label51.setBackground(new java.awt.Color(0, 255, 51));
        jPanel27.add(label51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, 10));

        label52.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label52.setText("59,996 Tk");
        jPanel27.add(label52, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jPanel28.setFocusable(false);
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label53.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label53.setText("Food");
        jPanel28.add(label53, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label54.setBackground(new java.awt.Color(255, 153, 0));
        jPanel28.add(label54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, 10));

        label55.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label55.setText("24,050 Tk");
        jPanel28.add(label55, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel27.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 160, 70));

        jPanel29.setFocusable(false);
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label56.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label56.setText("Food");
        jPanel29.add(label56, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label57.setBackground(new java.awt.Color(255, 153, 0));
        jPanel29.add(label57, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, 10));

        label58.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label58.setText("24,050 Tk");
        jPanel29.add(label58, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel30.setFocusable(false);
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label59.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label59.setText("Food");
        jPanel30.add(label59, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label60.setBackground(new java.awt.Color(255, 153, 0));
        jPanel30.add(label60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, 10));

        label61.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label61.setText("24,050 Tk");
        jPanel30.add(label61, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel29.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 160, 70));

        jPanel27.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 160, 70));

        jPanel10.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 160, 70));

        jPanel31.setBackground(new java.awt.Color(204, 204, 204));
        jPanel31.setFocusable(false);
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label62.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label62.setText("Bills & Utilities");
        jPanel31.add(label62, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label63.setBackground(new java.awt.Color(0, 153, 102));
        jPanel31.add(label63, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, 10));

        label64.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label64.setText("10,485 Tk");
        jPanel31.add(label64, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jPanel32.setFocusable(false);
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label65.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label65.setText("Food");
        jPanel32.add(label65, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label66.setBackground(new java.awt.Color(255, 153, 0));
        jPanel32.add(label66, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, 10));

        label67.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label67.setText("24,050 Tk");
        jPanel32.add(label67, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel31.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 160, 70));

        jPanel33.setFocusable(false);
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label68.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label68.setText("Food");
        jPanel33.add(label68, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label69.setBackground(new java.awt.Color(255, 153, 0));
        jPanel33.add(label69, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, 10));

        label70.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label70.setText("24,050 Tk");
        jPanel33.add(label70, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel34.setFocusable(false);
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label71.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label71.setText("Food");
        jPanel34.add(label71, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        label72.setBackground(new java.awt.Color(255, 153, 0));
        jPanel34.add(label72, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, 10));

        label73.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label73.setText("24,050 Tk");
        jPanel34.add(label73, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel33.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 160, 70));

        jPanel31.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 160, 70));

        jPanel10.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 160, 70));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 720, 280));

        MenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        MenuPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MenuPanel.setPreferredSize(new java.awt.Dimension(773, 68));

        rSButtonHover4.setBackground(new java.awt.Color(153, 51, 0));
        rSButtonHover4.setText("Monthly");
        rSButtonHover4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rSButtonHover4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover4ActionPerformed(evt);
            }
        });

        rSButtonHover5.setBackground(new java.awt.Color(153, 51, 0));
        rSButtonHover5.setText("Filter");
        rSButtonHover5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rSButtonHover5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover5ActionPerformed(evt);
            }
        });

        rSButtonHover6.setBackground(new java.awt.Color(102, 0, 102));
        rSButtonHover6.setText("Stats");
        rSButtonHover6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rSButtonHover6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover6ActionPerformed(evt);
            }
        });

        rSButtonHover7.setBackground(new java.awt.Color(153, 51, 0));
        rSButtonHover7.setText("Daily");
        rSButtonHover7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rSButtonHover7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover7ActionPerformed(evt);
            }
        });

        rSButtonHover8.setBackground(new java.awt.Color(153, 51, 0));
        rSButtonHover8.setText("X");
        rSButtonHover8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rSButtonHover8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover8ActionPerformed(evt);
            }
        });

        rSButtonHover9.setBackground(new java.awt.Color(153, 51, 0));
        rSButtonHover9.setText("Signout");
        rSButtonHover9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rSButtonHover9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover9ActionPerformed(evt);
            }
        });

        rSButtonHover10.setBackground(new java.awt.Color(153, 51, 0));
        rSButtonHover10.setText("HOME");
        rSButtonHover10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rSButtonHover10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover10ActionPerformed(evt);
            }
        });

        rSButtonHover11.setBackground(new java.awt.Color(153, 51, 0));
        rSButtonHover11.setText("Saving");
        rSButtonHover11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rSButtonHover11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover11ActionPerformed(evt);
            }
        });

        rSButtonHover12.setBackground(new java.awt.Color(51, 0, 153));
        rSButtonHover12.setText("MONEY MANAGER");
        rSButtonHover12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rSButtonHover12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover12ActionPerformed(evt);
            }
        });

        rSButtonHover13.setBackground(new java.awt.Color(153, 51, 0));
        rSButtonHover13.setText("Setting");
        rSButtonHover13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        rSButtonHover13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover13ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/money.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addComponent(rSButtonHover10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSButtonHover4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rSButtonHover7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rSButtonHover5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rSButtonHover6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rSButtonHover11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(rSButtonHover13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addComponent(rSButtonHover9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rSButtonHover12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSButtonHover8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rSButtonHover12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rSButtonHover8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSButtonHover5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonHover6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonHover9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonHover10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonHover7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonHover4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonHover11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonHover13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonHover4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover4ActionPerformed

    private void rSButtonHover5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover5ActionPerformed

    private void rSButtonHover6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover6ActionPerformed

    private void rSButtonHover7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover7ActionPerformed

    private void rSButtonHover8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover8ActionPerformed

        // TODO add your handling code here:
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover8ActionPerformed

    private void rSButtonHover9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover9ActionPerformed

    private void rSButtonHover10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover10ActionPerformed

    private void rSButtonHover11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover11ActionPerformed

    private void rSButtonHover12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover12ActionPerformed

    private void rSButtonHover13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover13ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Statistics().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel HistogramPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label2;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label23;
    private java.awt.Label label24;
    private java.awt.Label label25;
    private java.awt.Label label26;
    private java.awt.Label label27;
    private java.awt.Label label28;
    private java.awt.Label label29;
    private java.awt.Label label3;
    private java.awt.Label label30;
    private java.awt.Label label31;
    private java.awt.Label label32;
    private java.awt.Label label33;
    private java.awt.Label label34;
    private java.awt.Label label35;
    private java.awt.Label label36;
    private java.awt.Label label37;
    private java.awt.Label label38;
    private java.awt.Label label39;
    private java.awt.Label label4;
    private java.awt.Label label40;
    private java.awt.Label label41;
    private java.awt.Label label42;
    private java.awt.Label label43;
    private java.awt.Label label44;
    private java.awt.Label label45;
    private java.awt.Label label46;
    private java.awt.Label label47;
    private java.awt.Label label48;
    private java.awt.Label label49;
    private java.awt.Label label5;
    private java.awt.Label label50;
    private java.awt.Label label51;
    private java.awt.Label label52;
    private java.awt.Label label53;
    private java.awt.Label label54;
    private java.awt.Label label55;
    private java.awt.Label label56;
    private java.awt.Label label57;
    private java.awt.Label label58;
    private java.awt.Label label59;
    private java.awt.Label label6;
    private java.awt.Label label60;
    private java.awt.Label label61;
    private java.awt.Label label62;
    private java.awt.Label label63;
    private java.awt.Label label64;
    private java.awt.Label label65;
    private java.awt.Label label66;
    private java.awt.Label label67;
    private java.awt.Label label68;
    private java.awt.Label label69;
    private java.awt.Label label7;
    private java.awt.Label label70;
    private java.awt.Label label71;
    private java.awt.Label label72;
    private java.awt.Label label73;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Panel panelBarChart;
    private rojerusan.RSButtonHover rSButtonHover10;
    private rojerusan.RSButtonHover rSButtonHover11;
    private rojerusan.RSButtonHover rSButtonHover12;
    private rojerusan.RSButtonHover rSButtonHover13;
    private rojerusan.RSButtonHover rSButtonHover4;
    private rojerusan.RSButtonHover rSButtonHover5;
    private rojerusan.RSButtonHover rSButtonHover6;
    private rojerusan.RSButtonHover rSButtonHover7;
    private rojerusan.RSButtonHover rSButtonHover8;
    private rojerusan.RSButtonHover rSButtonHover9;
    // End of variables declaration//GEN-END:variables
}
